### ISSUE TITLE
Crash on ADR API16 (Grab has bugfix)

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#569] opened 2022-11-23 07:10 UTC
## Summary

SSL handshake aborted: ssl=0xb96a4e90:.Found solution here
https://github.com/square/okhttp/issues/2372#issuecomment-244807676

## Grab has bugfix
The original author of this bug report is Grab. They have a bug fix and would like to upstream it to MapLibre GL Native.

**Comment by ovivoda** [comment] 2023-01-28 13:38
@wipfli @alanchenboy do we have the steps to reproduce this issue?

**Comment by grab-liyanjin** [comment] 2023-01-30 03:19
The map will crash when running on the ADR API16 OS, you can try because our version is an old version, so not sure if this still happens in the new version

**Comment by louwers** [comment] 2023-03-23 22:39
Closing this for now.

Please re-open with a reproduction if it is still an issue.

**Closed by louwers** 2023-03-23 22:39 UTC
Labels: bug, more info needed, android, grab has bugfix
