### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by chrisballinger** [maplibre/maplibre-gl-native#4] opened 2021-01-16 19:10 UTC
The `Mapbox.xcframework` here is missing a slice for arm64 iOS Simulator: https://github.com/maptiler/maplibre-gl-native/releases/download/ios-v5.10.0/Mapbox-5.10.0.zip

For whatever reason arm64 iOS Simulator is already present in `MapboxMobileEvents.xcframework`, just not in `Mapbox.xcframework`.

![Screen Shot 2021-01-16 at 11 06 03 AM](https://user-images.githubusercontent.com/518687/104820647-313dd900-57eb-11eb-8a83-768db65cb8aa.png)

Although it doesn't look like you support macOS binaries yet, they'll also need arm64 slices whenever that day comes. I'd suggest just adding macOS support to the existing XCFramework.

**Comment by petr-pokorny-1** [comment] 2021-01-26 08:45
Thank you @chrisballinger for the report. I had to exclude arm64 architecture from build architectures because I was unable to link it. I am not sure what is the root issue - it might be that I am using Intel based mac and GitHub actions runners we use for CD/CI are also Intel based. Details on the issue on [StackOverflow](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios).

If you would have more knowledge on this topic let us know or place in a pull request.

To reproduce this issue, just remove excluded architectures and build the project.

![Screen Shot 2021-01-26 at 9 43 18 AM](https://user-images.githubusercontent.com/16223511/105821484-3523e500-5fbb-11eb-92c2-1c8477b0b80a.png)

**Comment by petr-pokorny-1** [comment] 2021-01-27 11:14
The issue seems to be cause by Mapbox dependencies dependencies which were removed in #7

**Comment by petr-pokorny-1** [comment] 2021-01-27 17:09
@chrisballinger can I close this issue? macOS support has its own ticket.

**Comment by chrisballinger** [comment] 2021-01-28 02:30
@petr-pokorny-1 After those changes, does the new final binary of `Mapbox.xcframework` now contain arm64 slices for iOS Simulator? If so, then I'd say this issue could be closed.

**Comment by petr-pokorny-1** [comment] 2021-02-20 17:53
I believe this was fixed in the following commits:
https://github.com/maplibre/maplibre-gl-native/commit/62c6178029cfe6dfb3bbb7bbd3da557da2cfe8d2
https://github.com/maplibre/maplibre-gl-native/commit/2f480bf8eea4f9267fc5b69aabc698a20083569f
https://github.com/maplibre/maplibre-gl-native/commit/117a4c589911ae68e850bb09b71289f1de9524a2

The framework now contains arm64 slices for iOS simulator. 

![Screenshot 2021-02-20 at 18 48 58](https://user-images.githubusercontent.com/16223511/108604216-d466ad00-73ac-11eb-94fd-e3b019ae5cd1.png)

The problem is that I don't have silicon mac to test it. We should release next version with these changes on March 05 so it would be great if someone could test it.

**Comment by chrisballinger** [comment] 2021-02-20 20:46
Awesome! Unfortunately I don't either, perhaps one of the macOS CI providers has ARM machines now?

**Comment by roblabs** [comment] 2021-02-21 17:11
I was able to build & test MapLibre on Apple Silicon, but the resulting test app had the following symptoms:

0.  MapLibre builds on Apple Silicon
1.  The Map renders, but **is very slow & sluggish**.  
2.  The log in Xcode is has multiple log entries related to `'cyclone'`.
3.  I'm not certain what from the log is significant, but here is a snippet.

```log
2021-02-21 08:28:00.694678-0800 GeographyClass[59356:2652990] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x600003fa42a0> to GL_RENDERBUFFER 1
2021-02-21 08:28:00.694810-0800 GeographyClass[59356:2652990] Failed to make complete framebuffer object 8cd6
'cyclone' is not a recognized processor for this target (ignoring processor)
'cyclone' is not a recognized processor for this target (ignoring processor)
# ... over 150 entries of this same log entry
'cyclone' is not a recognized processor for this target (ignoring processor)
```

---

Build tool chain

* macOS Big Sur 11.3 Beta (20E5186d)
* MapLibre compiled with Chip: Apple A12Z Bionic
* Xcode Version 12.4 (12D4e)
* Contents from the file `maplibre-gl-native/platform/ios/build/iOS/pkg/version.txt`
  * `https://github.com/maplibre/maplibre-gl-native/commit/62c6178029`
  * Using commit https://github.com/maplibre/maplibre-gl-native/commit/62c6178029

![image](https://user-images.githubusercontent.com/118112/108631818-a7ec7880-7420-11eb-8c9e-0138413d3243.png)

---

How to test:

If your Xcode project uses Swift package to import MapLibre, then delete the `Mapbox` & `MapboxMobileEvents` Libraries.

*Xcode Libraries before removing the working version with MapLibre from a Swift Package*

The [test app](https://github.com/roblabs/openmaptiles-ios-demo) has a working version with MapLibre, but is manually removed for this test. 

---

![image](https://user-images.githubusercontent.com/118112/108632266-dd926100-7422-11eb-8542-f57faaf34a8e.png)

---

*Xcode Libraries after a) removing Swift Package Libraries, and b) dragging and dropping `Mapbox.xcframework` built on Apple Silicon*

![image](https://user-images.githubusercontent.com/118112/108632269-e125e800-7422-11eb-9be2-3cab56bf0fa0.png)

**Comment by roman-mykitchak** [comment] 2021-04-29 13:31
Hi,
Apple introduced new iPad Pro featuring breakthrough M1 chip.
In such a reasons will we have a build with supported M1 architecture.
Will it work for mentioned iPad(iPadOS) as well?

Same question about Apple Silicon Mac build:
Will it be supported on "ARM-based system on the chip"?

**Comment by roblabs** [comment] 2021-07-22 03:21
MapLibre runs on the simulator on Apple Silicon with the latest Xcode release & beta.

Fixed with commit https://github.com/maplibre/maplibre-gl-native/commit/19b86f750dd829a1122a1df928709c70e62cbeeb &  see issue #14.

**Closed by roblabs** 2021-07-22 03:21 UTC
Labels: help wanted
