### ISSUE TITLE
Free build without the dependencies on proprietary libraries

### ISSUE THREAD

**Issue by jakoblm** [maplibre/maplibre-gl-native#482] opened 2022-09-17 21:17 UTC
Is there any progress on the free build without the dependencies on proprietary libraries?
I know this point has already been raised, but the issues have been closed. And apparently nothing is happening there? Some apps have already been partially removed from F-Droid for this reason, such as: Transportr, DeltaChat.

Are there any efforts to fix these problems on the part of MapLibre?

See also the following posts:
https://github.com/maplibre/maplibre-gl-native/issues/379
https://github.com/maplibre/maplibre-gl-native/issues/288
https://gitlab.com/fdroid/fdroidserver/-/issues/1004

**Comment by birkskyum** [comment] 2022-09-18 08:23
Thanks for pushing attention to this. duplicate of #379

**Closed by birkskyum** 2022-09-18 08:23 UTC
