### ISSUE TITLE
Replace local version of Variant with std c++17 variant

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-gl-native#1068] opened 2023-04-24 18:43 UTC
If I understood correctly, we have a local Mapbox version of Variant which anticipated the c++ standard.
Let's switch to the standard version if it can be done quickly.

**Comment by louwers** [comment] 2023-04-25 14:27
Duplicate of #893

**Closed by louwers** 2023-04-25 14:27 UTC
